### ISSUE TITLE
drop_vars can damage the data data frame

### ISSUE THREAD

**Issue by struckma** [aphalo/gginnards#1]
Thank you for your great general implementation to reduce `ggplot2` objects to their needed size, if you would not have done it already, I would have had to do it, great work!
#
However, in https://github.com/aphalo/gginnards/blob/master/R/data-manip.R#L95, you are missing `drop = FALSE`, so that data frames for plots that need only one variable, data looses its class and becomes a vector, so that we see errors like the following:

```r
Error in `geom_histogram()` at QualityIndicatorFunctions/R/acc_distributions.R:470:6:
! Problem while computing layer data.
ℹ Error occurred in the 1st layer.
Caused by error in `unrowname()`:
! Can only remove rownames from <data.frame> and <matrix> objects
```

you can easily reproduce this with the following code:

```r
library(ggplot2)
p <- ggplot(cars, aes(x = speed)) + geom_histogram()
gginnards::drop_vars(p)
```

I will, so far, work around this error in my package, but maybe, you could consider to fix that, I would be grateful. 

Thank you

Stephan

**Comment by aphalo** [comment]
Thanks Stephan! Sorry about this! Fix commited here in GitHub. Submited to CRAN as version 0.1.2.

**Comment by aphalo** [comment]
'gginnards' 0.1.2 is on its way to CRAN, i.e., it has passed all checks.
Once again, thanks!
